#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    lLiftPot,       sensorNone)
#pragma config(Sensor, in2,    mgPot,          sensorPotentiometer)
#pragma config(Sensor, in3,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    rLiftPot,       sensorPotentiometer)
#pragma config(Sensor, in5,    mgIn,           sensorLineFollower)
#pragma config(Sensor, in6,    yaw,            sensorNone)
#pragma config(Sensor, dgtl1,  rightEn,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, LCD,            sensorNone)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           liftMG,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lLift,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           fL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           fR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           bL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           bR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rLift,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          cL,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

const unsigned int THRESHOLD = 35;			//Threshold for motors to work

/* Eliminates motor whine on the drive during user control */
int axesFix(int remote) {
	if(abs(remote) >= THRESHOLD) 		//Returns 0 if the value does not pass the TRESHOLD constant
		return remote;
	else
		return 0;
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
}

/******************************************************************
/*
/*											 USER CONTROL
/*
*******************************************************************/

task usercontrol()
{
	motor[intake] = 40;
	while(1)
	{
		//Drive input:
		motor[fR] = motor[bR] = axesFix(vexRT[Ch2]);									//Sets the right motors equal to channel 2
		motor[fL] = motor[cL] = motor[bL] = axesFix(vexRT[Ch3]);			//Sets the left motors equal to channel 3

		//Claw input:
		if(vexRT[Btn6U])
			motor[claw] = -127;
		else if(vexRT[Btn6D])
			motor[claw] = 127;
		else
			motor[claw] = 0;

		//Lift input:
		if(vexRT[Btn5U])
			motor[rLift] = motor[lLift] = 127;
		else if(vexRT[Btn5D])
			motor[rLift] = motor[lLift] = -127;
		else
			motor[rLift] = motor[lLift] = 0;

		//Mobile goal lift input:
		if(vexRT[Btn7L])
			motor[liftMG] = 127;
		else if(vexRT[Btn7D])
			motor[liftMG] = -127;
		else
			motor[liftMG] = 0;

		//Intake
		if(vexRT[Btn7R])
			motor[intake] = 40;
		else if(vexRT[Btn7U])
			motor[intake] = -40;
	}
}
