#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    mgClawPot,      sensorPotentiometer)
#pragma config(Sensor, in3,    yaw,            sensorNone)
#pragma config(Sensor, dgtl1,  leftEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEn,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LCD,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           bL,            tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           fL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           bR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           fR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mgClawL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mgClawR,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "resources\tunes.h"

//Back left drive is in port 1
//Front left drive is in port 2
//Back right drive is in port 3
//Front right drive is in port 4
//Left lift is in port 5
//Right lift is in port 6
//Mobile goal claw left is in port 7
//Mobile goal claw right is in port 8



/******************************************************************
/*
/*											 USER CONSTANTS
/*
*******************************************************************/



const unsigned int THRESHOLD = 35;					//Threshold for motors to work
const unsigned int MG_CLAW_TOL = 2;					//Mobile goal claw tolerance for p-tuning
const unsigned int LIFT_TOL = 30;						//Lift tolerance for p-tuning

const unsigned int MG_CLAW_ACC_TOL = 80;		//The thousandths accuracy of the mobile goal claw
const unsigned int LIFT_ACC_TOL = 100;			//The thousandths accuracy of the lift

const unsigned int MG_CLAW_MAX = 3860;			//The maximum for the mobile goal claw potentiometer (claw completely open)
const unsigned int MG_CLAW_MIN = 300;				//The minimum for the mobile goal claw potentiometer (claw completely closed)

const unsigned int LIFT_MAX = 2660;					//The maximum for the lift potentiometer
const unsigned int LIFT_MIN = 830;					//The minimum for the lift potentiometer

const float P_MG_CLAW = 0.1;								//The p-value for the mobile goal claw's movement
const float P_LIFT = 0.15;									//The p-value for the lift's movement

//Enumerated type used for targets array in autonomous
enum targetTypes {
	MG_CLAW			= 0,
	LIFT				= 1,
	N_TARGETS		= 2
};

//Global Variables
unsigned int skillsToggleStateG = 0;				//Variable to check if skills is toggled
unsigned int skillsPressedG = 0;						//Variable to check if the skills button is pressed
unsigned int fieldSideToggleStateG = 0;			//Variable to check which field side the robot is on
unsigned int fieldSidePressedG = 0;					//Variable to check if the field side button is pressed



/******************************************************************
/*
/*											 FUNCTIONS
/*
*******************************************************************/



/* A generic conversion function for converting from a thousandths to a potentiometer
value, for either the lift or claw's right or left side*/
float thousandthsToPot(targetTypes type, int thousandths, tDirections side = left) {
	//Stores desired extrema as floats to avoid later unit conversions.
	float max = (type == LIFT) ? LIFT_MAX : MG_CLAW_MAX;
	float min = (type == LIFT) ? LIFT_MIN : MG_CLAW_MIN;
	//Performs the calcualations and returns the desired value
	return (min + (max - min) * ((float)thousandths / 1000));
}

/* A generic conversion function for converting from a side of a system
that uses a potentiometer as  */
float potToThousandths(targetTypes type, tDirections side = left) {
	float max = (type == LIFT) ? LIFT_MAX : MG_CLAW_MAX;
	float min = (type == LIFT) ? LIFT_MIN : MG_CLAW_MIN;
	float potVal = (type == LIFT) ? SensorValue[liftPot] : SensorValue[mgClawPot];
	//Performs the calculations and returns the desired value
	return 1000 * ((potVal - min) / (max - min));
}

/* P-tunes the mobile goal claw to a specified claw target, which is a thousandths value
* along the range of the claw.
* This version of the function is used during autonomous in conjunction with an array.*/
void pTuneMGClaw(int mgClawTarget) {
	//The claw motor is set equal to it's error multiplied by the p-value
	if(mgClawTarget > 1000)			//The claw target is corrected if it is above the maximum
		mgClawTarget = 1000;
	else if(mgClawTarget < 0)		//The claw target is corrected if it is below the minimum
		mgClawTarget = 0;
	//Finds the error mutplied by the p-value of the claw
	int mgClawError = P_MG_CLAW * (thousandthsToPot(MG_CLAW, mgClawTarget) - SensorValue[mgClawPot]);
	//The claw only p-tunes if the error is above the tolerance
	motor[mgClawL] = motor[mgClawR] = (abs(mgClawError) >= MG_CLAW_TOL) ? mgClawError : 0;
}

/* SEE void pTuneClaw(int clawTarget)
* The equivalent of the above function, but the target is passed by reference rather
* than by value.
* This version of the function is used during driver mode in conjunction with a local variable.*/
void pTuneMGClaw(int* mgClawTarget) {
	if(*mgClawTarget > 1000)
		*mgClawTarget = 1000;
	else if(*mgClawTarget < 0)
		*mgClawTarget = 0;
	int mgClawError = P_MG_CLAW * (thousandthsToPot(MG_CLAW, *mgClawTarget) - SensorValue[mgClawPot]);
	motor[mgClawL] = motor[mgClawR] = (abs(mgClawError) >= MG_CLAW_TOL) ? mgClawError : 0;
}

/* P-tunes the lift to a specified lift target, which is a thousandths value
* along the range of the lift.  The lift is at its maximum when the thousandths
* value is 0, and at its minimum when it is 1000.
* This version of the function is used during autonomous in conjunction with an array.*/
void pTuneLift(int liftTarget) {
	if(liftTarget > 1000)			//The lift target is corrected if it is above the maximum
		liftTarget = 1000;
	else if(liftTarget < 0)		//The lift target is corrected if it is below the minimum
		liftTarget = 0;
	//Finds the error mutplied by the p-value of both sides of the lift
	int Error = P_LIFT * (thousandthsToPot(LIFT, liftTarget) - SensorValue[liftPot]);
	//The lift only p-tunes if the error is above the tolerance
	motor[liftL] = motor[liftR] = (abs(Error) >= LIFT_TOL) ? Error : 0;
}

/* SEE void pTuneLift(int liftTarget)
* The equivalent of the above function, but the target is passed by reference rather
* than by value.
* This version of the function is used during driver mode in conjunction with a local variable.*/
void pTuneLift(int* liftTarget) {
	if(*liftTarget > 1000)
		*liftTarget = 1000;
	else if(*liftTarget < 0)
		*liftTarget = 0;
	int Error = P_LIFT * (thousandthsToPot(LIFT, *liftTarget) - SensorValue[liftPot]);
	motor[liftL] = motor[liftR] = (abs(Error) >= LIFT_TOL) ? Error : 0;
}

/* The robot drives a set distance in encoder ticks, given by enTarget.
* It uses a formula to drive at a speed scaled to the difference between
* the current displacement and the final displacement.  It then drives
* backwards to counteract any additional drift.  It p-tunes while doing so.*/
void waitDistance(const int* const targets, int enTarget) {
	SensorValue[rightEn] = 0;		//Encoders zeroed
	SensorValue[leftEn] = 0;
	clearTimer(T1);

	int drive = 0;							//Stores the speed the drive should travel at

	int a = 18;									//Variable that reduces drift when increased but also lowers speed

	/*The robot uses a formula to scale speed to position if the velocity would
	* be within the threshold to start driving, but otherwise sets the speed equal
	* to the minimum threshold otherwise.*/
	while(abs(SensorValue[leftEn]) < abs(enTarget) && time1[T1] < 5000) {
		drive = sgn(enTarget) * (a * log(-abs(SensorValue[leftEn]) + abs(enTarget)) + (127 - (a * log(abs(enTarget)))));
		if(sgn(enTarget) > 0 && drive < THRESHOLD) {
			drive = THRESHOLD;
		}
		else if(sgn(enTarget) < 0 && drive > -THRESHOLD) {
			drive = -THRESHOLD;
		}
		motor[bR] = motor[fR] = motor[bL] = motor[fL] = drive;
		pTuneMGClaw(targets[MG_CLAW]);		//P-tunes the claws and the lift while driving
		pTuneLift(targets[LIFT]);
	}

	//Motors drive backward briefly in order to counteract additional drift
	motor[bR] = motor[fR] = motor[bL] = motor[fL] = -sgn(enTarget) * THRESHOLD;
	wait1Msec(110);
	motor[bR] = motor[fR] = motor[bL] = motor[fL] = 0;
}

/* A function used in autonomous that tells the robot to rotate a certain amount
* in tenths of a degree, using the VEX gyro. */
void waitRotate(const int* const targets, int degrees10) {
	//Multiplies the limit switch for the fieldside by the degrees, so that it is on the left side if the switch is down
	SensorValue[yaw] = 0;
	clearTimer(T1);
	degrees10 *= (fieldSideToggleStateG * 2 - 1);

	int drive = 0;							//Contains the drive speed

	int a = 15;									//The intensity of the drive functoin

	/* Enacts the rotation to a set tenths of a degree (degrees10) while tuning the lift
	* The rotation speed is tuned to decrease on a slope from 127 to the treshold.
	* If it is past the threshold, it is set equal to the treshold, but with each side
	* rotating in a different direction. */
	if(degrees10 > 0) {
		while(SensorValue[yaw] < degrees10 && time1(T1) < 5000) {
			drive = sgn(degrees10) * (a * log(-abs(SensorValue[yaw]) + abs(degrees10)) + (90 - (a * log(abs(degrees10)))));
			if(abs(drive) > 90) {
				drive = sgn(degrees10) * 90;
			}
			else if(sgn(degrees10) > 0 && drive < THRESHOLD) {
				drive = THRESHOLD;
			}
			else if(sgn(degrees10) < 0 && drive > -THRESHOLD) {
				drive = -THRESHOLD;
			}
			motor[bR] = motor[fR] = drive;		//The right side moves forwards
			motor[bL] = motor[fL] = -drive;		//The left side moves backwards
			pTuneMGClaw(targets[MG_CLAW]);		//P-tunes the claws and the lift while rotating
			pTuneLift(targets[LIFT]);
		}
	}
	else {
		while(SensorValue[yaw] > degrees10) {
			drive = sgn(degrees10) * (a * log(-abs(SensorValue[yaw]) + abs(degrees10)) + (90 - (a * log(abs(degrees10)))));
			if(abs(drive) > 90) {
				drive = sgn(degrees10) * 90;
			}
			else if(sgn(degrees10) > 0 && drive < THRESHOLD) {
				drive = THRESHOLD;
			}
			else if(sgn(degrees10) < 0 && drive > -THRESHOLD) {
				drive = -THRESHOLD;
			}
			motor[bR] = motor[fR] = drive;		//The right side moves forwards
			motor[bL] = motor[fL] = -drive;		//The left side moves backwards
			pTuneMGClaw(targets[MG_CLAW]);		//P-tunes the claws and the lift while rotating
			pTuneLift(targets[LIFT]);
		}
	}
	//Turns off the drive motors when the rotation is complete
	motor[bR] = motor[fR] = -sgn(degrees10) * THRESHOLD;
	motor[bL] = motor[fL] = sgn(degrees10) * THRESHOLD;
	wait1Msec(110);
	motor[bR] = motor[fR] = motor[bL] = motor[fL] = 0;
}

/* A somewhat general function used in autonomous that changes the contents
* of the current target values for the lift and the claw, and then pTunes both
* the lift and claw with their new target values. */
void waitActions(int* targets, int mgClawTarget, int liftTarget) {
	//Assigns the contents of targets to the new lift and claw target values
	targets[MG_CLAW] = mgClawTarget;
	targets[LIFT] = liftTarget;
	//P-tunes the lift and claw
	pTuneMGClaw(targets[MG_CLAW]);
	pTuneLift(targets[LIFT]);
}

/* Sets targets equal to the new values, then continues to test to see if the claw is within
the range specified by tolerance, which is defined by the user or set equal to the default tolerance */
void testMGClaw(int* targets, int mgClawTarget, int liftTarget, int accuracy = MG_CLAW_ACC_TOL) {
	do {
		waitActions(targets, mgClawTarget, liftTarget);
	} while(potToThousandths(MG_CLAW) < mgClawTarget - accuracy || potToThousandths(MG_CLAW) > mgClawTarget + accuracy);
}

void setMGClaw(int* targets, int mgClawTarget, int accuracy = MG_CLAW_ACC_TOL) {
	testMGClaw(targets, mgClawTarget, targets[LIFT], accuracy);
}

/* Sets targets equal to the new values, then sets the claw and continues to tune
* the lift until it is within the range specified by the tolerance.
* The tolerance is set to be the default LIFT_ACC_TOL by default.*/
void testLift(int* targets, int mgClawTarget, int liftTarget, int accuracy = LIFT_ACC_TOL) {
	do {
		waitActions(targets, mgClawTarget, liftTarget);
	} while(potToThousandths(LIFT) < liftTarget - accuracy || potToThousandths(LIFT) > liftTarget + accuracy);
}

void setLift(int* targets, int liftTarget, int accuracy = LIFT_ACC_TOL) {
	testLift(targets, targets[MG_CLAW], liftTarget, accuracy);
}

/* Eliminates motor whine on the drive during user control */
int axesFix(int remote) {
	if(abs(remote) >= THRESHOLD) 		//Returns 0 if the value does not pass the TRESHOLD constant
		return remote;
	else
		return 0;
}



/******************************************************************
/*
/*											 TASKS
/*
*******************************************************************/



//Task for displaying the battery on the LCD Screen
task displayBattery()
{
	bool toggleSwitch = false;					//Toggle switch variable
	string mainBattery, backupBattery;	//Setup two strings
	while(1) {
		//Toggle switch code for turning on and off
		if(nLCDButtons) {
			toggleSwitch = !toggleSwitch;
			wait1Msec(500);
		}
		if(toggleSwitch) {
			bLCDBacklight = true;     		 	//Turn on LCD Backlight
			clearLCDLine(0);         		   	//Clear line 1 of the LCD
			clearLCDLine(1);          		 	//Clear line 2 of the LCD

			//Display the Primary Robot battery voltage
			displayLCDString(0, 0, "Primary: ");
			sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
			displayNextLCDString(mainBattery);

			//Display the Backup battery voltage
			displayLCDString(1, 0, "Backup: ");
			sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
			displayNextLCDString(backupBattery);

			//Short delay for the LCD refresh rate
			wait1Msec(100);
		}
		else {
			bLCDBacklight = false;     		 	//Turn off LCD Backlight
			clearLCDLine(0);         		   	//Clear line 1 of the LCD
			clearLCDLine(1);          		 	//Clear line 2 of the LCD
		}
	}
}

task calibrateGyro()
{
	SensorType[yaw] = sensorNone;			//Resets the gyroscope
	wait1Msec(1100);									//Provides time for calibration
	SensorType[yaw] = sensorGyro;			//Reassigns the yaw gyroscope's sensor type
	wait1Msec(1100);									//Waits for the gyro to calibrate

	SensorValue[rightEn] = 0;					//Zeroes the right encoder
	SensorValue[leftEn] = 0;					//Zeroes the left encoder
	playTone(1200, 50);								//Plays a tone when calibration is finished to alert the operator
}



/******************************************************************
/*
/*											 AUTONOMOUS CODE
/*
*******************************************************************/



void pre_auton()
{
	bStopTasksBetweenModes = false;
	startTask(calibrateGyro);

	int* fieldSideToggleStateL = &fieldSideToggleStateG;
	int* fieldSidePressedL = &fieldSidePressedG;
	int* skillsToggleStateL = &skillsToggleStateG;
	int* skillsPressedL = &skillsPressedG;

	bLCDBacklight = true;			//Turn the backlight for the LCD On

	//Default messasges
	displayLCDString(0, 0, "Auton Settings:");
	displayLCDString(1, 0, "L      NoSk     ");

	while(1) {
		//Check for the left button being pressed if the button isn't already pressed
		if((nLCDButtons & leftBtnVEX) && !(*fieldSidePressedL)) {
			*fieldSideToggleStateL = 1 - *fieldSideToggleStateL;		//Change the toggle state
			*fieldSidePressedL = 1;																//Note that the button is pressed
		}
		//If the left button isn't pressed
		else if (!(nLCDButtons & leftBtnVEX)) {
			*fieldSidePressedL = 0;																//Note that the button is not pressed
		}

		//Same toggle switch with another button
		if((nLCDButtons & centerBtnVEX) && !(*skillsPressedL)) {
			*skillsToggleStateL = 1 - *skillsToggleStateL;
			*skillsPressedL = 1;
		}
		else if (!(nLCDButtons & centerBtnVEX)) {
			*skillsPressedL = 0;
		}

		//Print various messages depending on the button state
		if(*fieldSideToggleStateL)
			displayLCDString(1, 0, "R");
		else if(!(*fieldSideToggleStateL))
			displayLCDString(1, 0, "L");
		if(*skillsToggleStateL)
			displayLCDString(1, 7, "NoSk");
		else if(!(*skillsToggleStateL))
			displayLCDString(1, 7, "Sk  ");
	}
}

task autonomous()
{
	//targets is an array of integers that stores the target values for the lift, cone claw, mobile goal claw, and rotation of the cone claw
	int targets[N_TARGETS] = {1000, 0};	//NOTE- CHANGE THESE DEFAULTS LATER!!!

	// Skills Autonomous
	if(skillsToggleStateG) {
	}

	//Regular Autonomous
	else {
	}
}



/******************************************************************
/*
/*											 USER CONTROL
/*
*******************************************************************/



task usercontrol()
{
	startTask(manageMusic);													//Plays randomly-chosen music in the last seconds of a match
	startTask(displayBattery);											//Display the battery voltage

	int liftTarget = potToThousandths(LIFT);				//The lift target starts wherever the lift is
	int mgClawTarget = potToThousandths(MG_CLAW);			//The cone claw target starts where the cone claw is

	int cClawToggleState = 0;					//Variable to check if the cone claw is toggled
	int cClawPressed = 0;							//Variable to check if the cone claw button is pressed
	int cClawRotToggleState = 0;			//Variable to check if the claw rotation is toggled

	clearTimer(T1);

	while (1)
	{
		//The drive:
		motor[fR] = motor[bR] = axesFix(vexRT[Ch2]);
		motor[fL] = motor[bL] = axesFix(vexRT[Ch3]);

		//Lift input:
		if(vexRT[Btn5U] || vexRT[Btn5D])							//5U and 5D shoulder buttons increment and decrement the lift target
			liftTarget -= (vexRT[Btn5U] - vexRT[Btn5D]);

		pTuneLift(&liftTarget);												//P-tunes the lift

		//Mobile Goal claw input:
		if(vexRT[Btn6U] || vexRT[Btn6D])							//The claw target is maintained or changed if certain conditions are met
			mgClawTarget -= (vexRT[Btn6U] - vexRT[Btn6D]);

		pTuneMGClaw(&mgClawTarget);										//P-tunes the cone claw
	}
}
